name: NBA Daily Update
on:
  schedule:
    - cron: '0 9 * * *'  # Runs daily at 9 AM UTC
  push:
    branches: [ "main" ]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install pandas nba_api pytest
      - run: mkdir -p data
      - run: python scripts/fetch_games.py
      - run: pytest tests/
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          force_orphan: true
          keep_files: false